import type {
  Attrs,
  AttrsPatch,
  Node,
  NodeId,
  NodeInit,
  PortDirection,
  PortId,
  ReadAttrs,
} from '@dagr/graph';

/**
 * A port as a node kind declares it, rather than as a node carries it.
 *
 * `@dagr/graph`'s `Port` is what a node has; this is what every node of
 * a kind is promised to have. The two differ by `maxEdges`, which is a rule
 * about a port and not a property of one, and which the graph model has no
 * business enforcing: `Graph` permits any topology by design.
 */
export interface PortSpec {
  readonly id: PortId;
  readonly direction: PortDirection;
  /**
   * The most edges this port accepts. Absent means unbounded.
   *
   * A cap rather than the usual `'single' | 'multiple'` word, for two reasons.
   * A number is the general case and the word is the two useful values of it,
   * so nothing is lost, and a union declared here is a union every consumer's
   * exhaustive `switch` breaks on when a third case arrives, which is the
   * hazard M5.5's entry plans to document `PatchOp` as an open union to
   * escape. Absent rather
   * than `Infinity` because `Infinity` does not survive `JSON.stringify`, and a
   * spec a consumer cannot serialise is a spec they cannot ship a fixture of.
   *
   * ENFORCEMENT IS M6.2's, not this task's: a spec says what the rule is and
   * connection validation is where a proposed edge meets it. What this package
   * does today is refuse a value M6.2 could not act on, so the number M6.2
   * reads is a positive integer or nothing.
   */
  readonly maxEdges?: number;
}

/**
 * A consumer's own validator for one kind's configuration.
 *
 * It is handed the node's whole attribute bag, because which keys are
 * configuration is the consumer's question and not Dagr's: a toolkit that
 * decided it would be defining the ontology this milestone exists not to
 * define. An empty result is a valid config, and every string is a problem to
 * put in front of a user.
 *
 * Strings rather than a structured issue type, deliberately. A structured
 * form is a schema format of Dagr's invention by another name, and the
 * consumer already has one: this is where `zod`'s `issues`, `valibot`'s, or a
 * hand-written check hands its own message across.
 */
export type ConfigCheck = (attrs: ReadAttrs<Attrs>) => readonly string[];

/**
 * A node kind as a consumer declares it, with the kind itself left out: the
 * key it is declared under IS the kind, so it is written once.
 */
export interface NodeSpecInit {
  /** Defaults to none. Port ids are unique within a kind. */
  readonly ports?: readonly PortSpec[];
  /** Defaults to none, which reports every config as valid. */
  readonly checkConfig?: ConfigCheck;
}

/**
 * A node kind as the registry hands it back. Frozen, including its ports.
 *
 * `K` is the consumer's own union of kinds, inferred once from the object
 * literal handed to {@link defineRegistry} and threaded through everything
 * downstream. That threading is the whole point of the type parameter: a
 * hover or drag callback given a `NodeSpec<'source' | 'filter'>` can switch on
 * `kind` exhaustively, and one given a `NodeSpec<string>` cannot.
 */
export interface NodeSpec<K extends string = string> {
  readonly kind: K;
  readonly ports: readonly PortSpec[];
  readonly checkConfig?: ConfigCheck;
}

/** How a registry departs from its defaults. */
export interface RegistryOptions {
  /**
   * The node attribute a kind is read from. Defaults to `'kind'`.
   *
   * A key, not an ontology: Dagr has to look somewhere to answer "what kind is
   * this node", and the somewhere is configurable precisely so a consumer with
   * an existing attribute vocabulary does not have to rename it.
   */
  readonly kindKey?: string;
}

/**
 * What a caller may add to a node the registry builds.
 *
 * `A` is the caller's own node attribute type, the one their `Graph` is
 * parameterised by, so the attributes they pass are checked against it exactly
 * as `graph.addNode` would check them. Ports are absent on purpose: see
 * {@link NodeRegistry.nodeInit}.
 */
export interface KindNodeInit<A extends object = Attrs> {
  /** Generated by `Graph` when absent, as usual. */
  readonly id?: NodeId;
  readonly attrs?: AttrsPatch<A>;
}

/**
 * The kinds a consumer declared, and the answers Dagr gives about them.
 *
 * Every method taking a kind takes `K`, so a kind that was never declared is a
 * compile error rather than a runtime one. {@link NodeRegistry.has} is the one
 * door from `string` into `K`, and it is a real membership test rather than a
 * cast, which is what makes the narrowing honest.
 */
export interface NodeRegistry<K extends string = string> {
  /** The declared kinds, in declaration order. Frozen. */
  readonly kinds: readonly K[];
  /** The node attribute this registry reads a kind from. */
  readonly kindKey: string;
  /** Whether a string names a declared kind, narrowing it when it does. */
  has(kind: string): kind is K;
  /** The spec for a declared kind. Total over `K`, so it cannot fail. */
  get(kind: K): NodeSpec<K>;
  /** One declared port of a kind, or `undefined` when the kind has no such port. */
  port(kind: K, portId: PortId): PortSpec | undefined;
  /** The kind of a node, or `undefined` when it does not legibly declare one. */
  kindOf<A extends object>(node: Node<A>): K | undefined;
  /** The spec of a node. Throws rather than guessing. */
  resolve<A extends object>(node: Node<A>): NodeSpec<K>;
  /** The spec of a node, or `undefined` where {@link NodeRegistry.resolve} would throw. */
  tryResolve<A extends object>(node: Node<A>): NodeSpec<K> | undefined;
  /**
   * What the node's own kind says is wrong with its configuration. Empty means
   * nothing, and a kind that declared no check always reports nothing.
   *
   * Resolves first, so a node of an undeclared kind throws rather than passing
   * validation by having no validator.
   */
  checkConfig<A extends object>(node: Node<A>): readonly string[];
  /**
   * A `NodeInit` for a new node of this kind: the declared ports, the kind
   * attribute, and whatever the caller adds.
   *
   * The kind attribute is written LAST, so `attrs` cannot mislabel the node it
   * is building. Ports are not takeable from the caller: the spec is what says
   * which ports a kind has, and a node that quietly gained one would resolve to
   * a spec that does not describe it.
   *
   * `A` comes from the caller, usually inferred from the `Graph` the result is
   * handed to, so the attributes they pass are checked against their own type.
   * A consumer whose attribute type declares the kind key (`kind: 'source' |
   * 'filter'`, typically) has it checked like any other key; one whose type
   * does not still gets the attribute written, because `Graph` stores what it
   * is given and the registry has to be able to read the node back.
   */
  nodeInit<A extends object = Attrs>(kind: K, init?: KindNodeInit<A>): NodeInit<A>;
}

